import { useEffect, useState, type CSSProperties, type ReactNode } from 'react';
import { BarChart3, Bell, BookOpen, CalendarDays, CircleHelp, Home, LogOut, MapPin, Menu, Palette, Plus, Settings2, Sparkles, X } from 'lucide-react';
import type { Role } from '../types';
import type { Appointment } from '../types';
import { defaultTheme, type ThemeConfig } from '../theme';

export type View = 'today' | 'new' | 'scan' | 'report' | 'passport' | 'appointments' | 'studio' | 'salon';
export function StudioLayout({ view, setView, role, onLogout, notifications, children }: { view: View; setView: (view: View) => void; role: Role; onLogout: () => void; notifications: Appointment[]; children: ReactNode }) {
  const [mobileNav, setMobileNav] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [guideOpen, setGuideOpen] = useState(false);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [theme, setTheme] = useState<ThemeConfig>(() => { try { return { ...defaultTheme, ...JSON.parse(localStorage.getItem('halo-theme') || '{}') }; } catch { return defaultTheme; } });
  useEffect(() => { localStorage.setItem('halo-theme', JSON.stringify(theme)); }, [theme]);
  const go = (next: View) => { setView(next); setMobileNav(false); };
  const cssVars = { '--rust': theme.primary, '--dark': theme.sidebar, '--cream': theme.surface, '--ink': theme.ink } as CSSProperties;
  return <div className="app" style={cssVars}><aside className={mobileNav ? 'sidebar open' : 'sidebar'}><div className="brand">{theme.logoUrl ? <img className="brand-image" src={theme.logoUrl} alt={theme.brandName}/> : <span className="brand-mark">{theme.logoMark}</span>}<div><strong>{theme.brandName}</strong><small>CONSULTATION STUDIO</small></div></div><nav><p>{role === 'admin' ? 'STUDIO WORKSPACE' : 'YOUR SPACE'}</p>{role === 'admin' ? <><Nav active={view === 'today'} icon={<Home size={16}/>} label="Today" onClick={() => go('today')}/><Nav active={view === 'studio'} icon={<BarChart3 size={16}/>} label="Studio data" onClick={() => go('studio')}/><Nav active={view === 'new' || view === 'scan' || view === 'report'} icon={<Plus size={17}/>} label="New consultation" onClick={() => go('new')}/><Nav active={view === 'passport'} icon={<BookOpen size={16}/>} label="Hair Passports" badge="24" onClick={() => go('passport')}/></> : <Nav active={view === 'appointments'} icon={<CalendarDays size={16}/>} label="My appointments" onClick={() => go('appointments')}/>}</nav><div className="halo-note"><Sparkles size={15}/><b>{theme.brandName} note</b><p>The best consultation leaves the guest feeling understood before the scissors come out.</p></div><div className="profile"><span className="avatar yellow">{role === 'admin' ? 'MN' : 'AR'}</span><div><b>{role === 'admin' ? 'Meera Nair' : 'Ananya Rao'}</b><small>{role === 'admin' ? 'Senior stylist · Admin' : 'Guest account'}</small></div><button className="logout-button" title="Sign out" onClick={onLogout}><LogOut size={15}/></button></div></aside><main><header><button className="icon-button menu" onClick={() => setMobileNav(!mobileNav)}><Menu size={20}/></button><div className="crumb"><MapPin size={15}/>Indiranagar, Bengaluru <i>/</i> Studio 01</div><div className="top-actions"><button className="quick-guide-trigger" onClick={() => setGuideOpen(true)}><CircleHelp size={16}/><span>Quick guide</span></button><button className="notification-trigger" title="Open notifications" onClick={() => setNotificationsOpen(!notificationsOpen)}><Bell size={17}/>{role === 'admin' && notifications.length > 0 && <em>{notifications.length}</em>}</button><button className="settings-trigger" title="Customize theme and logo" onClick={() => setSettingsOpen(!settingsOpen)}><Palette size={17}/></button><i></i><b>{role === 'admin' ? 'Tuesday, 18 June' : 'Welcome, Ananya'}<small>{role === 'admin' ? '10:12 AM' : 'Guest account'}</small></b></div></header>{settingsOpen && <ThemePanel theme={theme} onChange={setTheme} onClose={() => setSettingsOpen(false)}/>} {notificationsOpen && <NotificationPanel role={role} notifications={notifications} onClose={() => setNotificationsOpen(false)}/>} {guideOpen && <QuickGuide role={role} onClose={() => setGuideOpen(false)}/>} {children}</main></div>;
}
function Nav({ active, icon, label, badge, onClick }: { active: boolean; icon: ReactNode; label: string; badge?: string; onClick: () => void }) { return <button className={active ? 'nav-item active' : 'nav-item'} onClick={onClick}>{icon}<span>{label}</span>{badge && <em>{badge}</em>}</button>; }

export function ThemePanel({ theme, onChange, onClose }: { theme: ThemeConfig; onChange: (theme: ThemeConfig) => void; onClose: () => void }) {
  const update = (key: keyof ThemeConfig, value: string) => onChange({ ...theme, [key]: value });
  return <aside className="theme-panel"><div className="theme-panel-head"><div><label>STUDIO CUSTOMIZATION</label><h2>Make it yours</h2></div><button className="icon-button" onClick={onClose} title="Close customization"><X size={17}/></button></div><label className="theme-field-label">Brand name</label><input value={theme.brandName} onChange={e => update('brandName', e.target.value)} placeholder="Your studio name"/><label className="theme-field-label">Logo image URL</label><input value={theme.logoUrl} onChange={e => update('logoUrl', e.target.value)} placeholder="https://... (optional)"/><div className="theme-inline"><div><label className="theme-field-label">Logo mark</label><input maxLength={2} value={theme.logoMark} onChange={e => update('logoMark', e.target.value)} /></div><div><label className="theme-field-label">Primary</label><input className="color-input" type="color" value={theme.primary} onChange={e => update('primary', e.target.value)} /></div></div><div className="theme-inline"><div><label className="theme-field-label">Sidebar</label><input className="color-input" type="color" value={theme.sidebar} onChange={e => update('sidebar', e.target.value)} /></div><div><label className="theme-field-label">Surface</label><input className="color-input" type="color" value={theme.surface} onChange={e => update('surface', e.target.value)} /></div></div><button className="theme-reset" onClick={() => onChange(defaultTheme)}>Reset to Halo theme</button></aside>;
}

function QuickGuide({ role, onClose }: { role: Role; onClose: () => void }) {
  const steps = role === 'admin' ? [['01', 'Start with the person', 'Open New consultation and capture the guest’s goal, length, and texture.'], ['02', 'Capture the full picture', 'Use the guided front, left, right, and optional back scan.'], ['03', 'Review together', 'Use the report, service suggestions, and try-on as conversation starters.'], ['04', 'Keep the relationship', 'Save decisions, notes, favorites, and service history in Hair Passport.']] : [['01', 'Choose a service', 'Select the appointment type that best matches what you want to discuss.'], ['02', 'Request a time', 'Choose a preferred date, time, stylist, and add useful notes.'], ['03', 'Wait for confirmation', 'Your request appears under My appointments while the studio confirms it.'], ['04', 'Build your passport', 'Your saved styles and visit history help future consultations feel familiar.']];
  return <div className="guide-backdrop" onClick={onClose}><section className="quick-guide-panel" onClick={event => event.stopPropagation()}><div className="theme-panel-head"><div><label>{role === 'admin' ? 'STYLIST WORKSPACE' : 'GUEST WORKSPACE'}</label><h2>How Halo works</h2></div><button className="icon-button" onClick={onClose} title="Close guide"><X size={17}/></button></div><p className="guide-intro">A calm path from context to a more confident hair decision.</p>{steps.map(step => <div className="guide-step" key={step[0]}><span>{step[0]}</span><div><b>{step[1]}</b><p>{step[2]}</p></div></div>)}<button className="primary wide" onClick={onClose}>Got it</button></section></div>;
}

function NotificationPanel({ role, notifications, onClose }: { role: Role; notifications: Appointment[]; onClose: () => void }) {
  return <div className="notification-panel"><div className="theme-panel-head"><div><label>{role === 'admin' ? 'STUDIO NOTIFICATIONS' : 'APPOINTMENT UPDATES'}</label><h2>{notifications.length ? `${notifications.length} new request${notifications.length === 1 ? '' : 's'}` : 'All caught up'}</h2></div><button className="icon-button" onClick={onClose} title="Close notifications"><X size={17}/></button></div>{notifications.length === 0 ? <p className="notification-empty">New appointment requests will appear here.</p> : notifications.map(appointment => <div className="notification-item" key={appointment.id}><span className="notification-dot"/><div><b>{appointment.service}</b><p>{appointment.date} · {appointment.time} · {appointment.stylist}</p><small>{role === 'admin' ? 'Guest appointment request' : appointment.status}</small></div></div>)}</div>;
}
