import { useMemo, useState } from 'react';
import { ArrowUpRight, Check, Search, Settings2, Users, WalletCards } from 'lucide-react';
import { ShellTitle } from '../components/ShellTitle';
import type { DashboardSummary } from '../types';

export function AdminStudioScreen({ data, onOpenPassport, onOpenSalon }: { data: DashboardSummary; onOpenPassport: () => void; onOpenSalon: () => void }) {
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => data.customers.filter(customer => customer.name.toLowerCase().includes(query.toLowerCase())), [data.customers, query]);
  return <section className="page studio-data"><ShellTitle eyebrow="THE STUDIO AT A GLANCE" title="A clearer view of the work." copy="Keep an eye on consultations, customer relationships and the services guests are choosing." action={<button className="soft" onClick={onOpenSalon}>Set up salon <Settings2 size={15}/></button>}/><div className="data-stats"><div className="panel data-stat"><Users size={18}/><span>Consultations</span><strong>{data.consultations}</strong><small><ArrowUpRight size={13}/> From PostgreSQL</small></div><div className="panel data-stat"><Check size={18}/><span>Service conversion</span><strong>{data.serviceConversion}%</strong><small><ArrowUpRight size={13}/> From PostgreSQL</small></div><div className="panel data-stat"><WalletCards size={18}/><span>Average visit value</span><strong>₹{data.averageVisitValue.toLocaleString('en-IN')}</strong><small><ArrowUpRight size={13}/> From PostgreSQL</small></div></div><div className="data-grid"><section className="panel customer-table"><div className="panel-head"><div><label>THE CLIENT BOOK</label><h2>Customer search</h2></div><div className="search-field"><Search size={15}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search guests"/></div></div>{filtered.map(customer => <div className="customer-row" key={customer.name}><span className="avatar sage">{customer.name.split(' ').map(part => part[0]).join('')}</span><div><b>{customer.name}</b><small>{customer.profile}</small></div><span><small>Last visit</small><b>{customer.last}</b></span><span><small>Visits</small><b>{customer.visits}</b></span><button className="text-button" onClick={onOpenPassport}>Open passport</button></div>)}{filtered.length === 0 && <p className="no-results">No database customers match that search.</p>}</section><section className="panel catalog"><div className="panel-head"><div><label>SERVICE CATALOG</label><h2>What guests choose</h2></div><button className="soft" onClick={onOpenSalon}>Edit catalog</button></div>{data.services.map(service => <div className="service-row" key={service.name}><div><b>{service.name}</b><small>{service.bookings} bookings</small></div><strong>{service.revenue}</strong><Check size={15}/></div>)}</section></div></section>;
}
