import { useMemo, useState } from 'react';
import { ArrowUpRight, Check, Search, Users, WalletCards } from 'lucide-react';
import { ShellTitle } from '../components/ShellTitle';

const customers = [{ name: 'Ananya Rao', profile: 'Wavy · Shoulder length', last: '18 Jun 2024', visits: 4 }, { name: 'Rohan Mehta', profile: 'Straight · Medium length', last: '14 Jun 2024', visits: 2 }, { name: 'Divya Krishnan', profile: 'Curly · Long length', last: '10 Jun 2024', visits: 7 }, { name: 'Kavya Iyer', profile: 'Wavy · Chin length', last: '03 Jun 2024', visits: 1 }];
const services = [{ name: 'Signature cut', bookings: 38, revenue: '₹28,500' }, { name: 'Conditioning finish', bookings: 24, revenue: '₹16,800' }, { name: 'Anti-frizz treatment', bookings: 19, revenue: '₹22,800' }];

export function AdminStudioScreen({ onOpenPassport }: { onOpenPassport: () => void }) {
  const [query, setQuery] = useState(''); const [catalog, setCatalog] = useState(services);
  const filtered = useMemo(() => customers.filter(customer => customer.name.toLowerCase().includes(query.toLowerCase())), [query]);
  return <section className="page studio-data"><ShellTitle eyebrow="THE STUDIO AT A GLANCE" title="A clearer view of the work." copy="Keep an eye on consultations, customer relationships and the services guests are choosing." action={<span className="ready-pill">JUNE 2024</span>}/><div className="data-stats"><div className="panel data-stat"><Users size={18}/><span>Consultations</span><strong>48</strong><small><ArrowUpRight size={13}/> 18% from last month</small></div><div className="panel data-stat"><Check size={18}/><span>Service conversion</span><strong>72%</strong><small><ArrowUpRight size={13}/> 8% from last month</small></div><div className="panel data-stat"><WalletCards size={18}/><span>Average visit value</span><strong>₹1,840</strong><small><ArrowUpRight size={13}/> 12% from last month</small></div></div><div className="data-grid"><section className="panel customer-table"><div className="panel-head"><div><label>THE CLIENT BOOK</label><h2>Customer search</h2></div><div className="search-field"><Search size={15}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search guests"/></div></div>{filtered.map(customer => <div className="customer-row" key={customer.name}><span className="avatar sage">{customer.name.split(' ').map(part => part[0]).join('')}</span><div><b>{customer.name}</b><small>{customer.profile}</small></div><span><small>Last visit</small><b>{customer.last}</b></span><span><small>Visits</small><b>{customer.visits}</b></span><button className="text-button" onClick={onOpenPassport}>Open passport</button></div>)}{filtered.length === 0 && <p className="no-results">No guests match that search.</p>}</section><section className="panel catalog"><div className="panel-head"><div><label>SERVICE CATALOG</label><h2>What guests choose</h2></div><button className="soft" onClick={() => setCatalog([...catalog, { name: 'New service', bookings: 0, revenue: '₹0' }])}>+ Add service</button></div>{catalog.map(service => <div className="service-row" key={service.name}><div><b>{service.name}</b><small>{service.bookings} bookings</small></div><strong>{service.revenue}</strong><Check size={15}/></div>)}</section></div></section>;
}
