import { useState } from 'react';
import { CalendarDays, Check, Clock3, Plus, Scissors } from 'lucide-react';
import { ShellTitle } from '../components/ShellTitle';
import type { Appointment } from '../types';

export function AppointmentsScreen({ appointments, onCreate }: { appointments: Appointment[]; onCreate: (appointment: Appointment) => void }) {
  const [service, setService] = useState('Signature cut'); const [date, setDate] = useState('2026-10-03'); const [time, setTime] = useState('10:30 AM'); const [stylist, setStylist] = useState('Meera Nair'); const [notes, setNotes] = useState('');
  const submit = () => { onCreate({ id: `appointment-${Date.now()}`, guestName: 'Ananya Rao', service, date, time, stylist, notes, status: 'Requested' }); setNotes(''); };
  return <section className="page appointments"><ShellTitle eyebrow="YOUR HAIR, YOUR TIME" title="Make space for your next visit." copy="Choose a time that feels good. Your stylist will confirm the details shortly." action={<span className="guest-pill">GUEST VIEW</span>}/><div className="appointments-grid"><section className="panel appointment-form"><div className="section-label"><span className="round-icon peach"><CalendarDays size={16}/></span><div><b>Book an appointment</b><small>A few details and you’re on your way.</small></div></div><div className="field"><label>What would you like to book?</label><select value={service} onChange={e => setService(e.target.value)}><option>Signature cut</option><option>Texture refresh</option><option>Colour consultation</option><option>Gloss refresh</option></select></div><div className="form-two"><div className="field"><label>Preferred date</label><input type="date" value={date} onChange={e => setDate(e.target.value)}/></div><div className="field"><label>Preferred time</label><select value={time} onChange={e => setTime(e.target.value)}><option>10:30 AM</option><option>11:15 AM</option><option>12:00 PM</option><option>01:30 PM</option></select></div></div><div className="field"><label>Preferred stylist</label><select value={stylist} onChange={e => setStylist(e.target.value)}><option>Meera Nair</option><option>Arjun S.</option><option>Nidhi Rao</option></select></div><div className="field"><label>Anything you’d like us to know?</label><textarea className="appointment-notes" value={notes} onChange={e => setNotes(e.target.value)} placeholder="Tell us about your hair goals..."/></div><button className="primary wide" onClick={submit}><Plus size={17}/>Request appointment</button></section><section><div className="appointment-intro"><Scissors size={22}/><label>YOUR STUDIO, REMEMBERED</label><h2>Every visit starts with context.</h2><p>Your notes, preferences, and favourite styles help the Halo team make the next conversation feel familiar.</p></div><section className="panel upcoming"><label>UPCOMING VISITS</label>{appointments.length === 0 && <div className="empty-appointments"><Clock3 size={19}/><p>No appointments yet.<br/>Your next good hair day can start here.</p></div>}{appointments.map(appointment => <div className="appointment-card" key={appointment.id}><div className="appointment-date"><b>{new Date(`${appointment.date}T00:00:00`).toLocaleDateString('en-IN', { day: '2-digit' })}</b><small>{new Date(`${appointment.date}T00:00:00`).toLocaleDateString('en-IN', { month: 'short' })}</small></div><div><b>{appointment.service}</b><p>{appointment.time} · {appointment.stylist}</p><span className="requested"><i/> {appointment.status}</span></div><Check size={16}/></div>)}</section></section></div></section>;
}
