import { useEffect, useState, type CSSProperties } from 'react';
import { ArrowRight, Check, LockKeyhole, Palette, Sparkles, UserRound } from 'lucide-react';
import { ThemePanel } from '../components/StudioLayout';
import { defaultTheme, type ThemeConfig } from '../theme';
import type { Role } from '../types';
import { request } from '../api';

export function LoginScreen({ onLogin, onGoogleLogin, error }: { onLogin: (email: string, password: string, role: Role, theme: ThemeConfig) => void | Promise<void>; onGoogleLogin: (credential: string, role: Role) => void | Promise<void>; error?: string }) {
  const [role, setRole] = useState<Role>('user');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [theme, setTheme] = useState<ThemeConfig>(defaultTheme);
  const [settingsOpen, setSettingsOpen] = useState(false);
  useEffect(() => { void request<ThemeConfig>('/salon/theme').then(savedTheme => setTheme({ ...defaultTheme, ...savedTheme })).catch(() => undefined); }, []);
  useEffect(() => { const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID; if (!clientId) return; const script = document.createElement('script'); script.src = 'https://accounts.google.com/gsi/client'; script.async = true; script.onload = () => { window.google?.accounts.id.initialize({ client_id: clientId, callback: response => { if (response.credential) void onGoogleLogin(response.credential, role); } }); const target = document.querySelector('.google-login'); if (target instanceof HTMLElement) window.google?.accounts.id.renderButton(target, { theme: 'outline', size: 'large', width: 400, text: 'continue_with' }); }; document.head.appendChild(script); return () => script.remove(); }, [onGoogleLogin, role]);
  const cssVars = { '--rust': theme.primary, '--dark': theme.sidebar, '--cream': theme.surface, '--ink': theme.ink } as CSSProperties;
  const logo = theme.logoUrl ? <img className="brand-image" src={theme.logoUrl} alt={theme.brandName}/> : <span className="brand-mark">{theme.logoMark}</span>;
  const googleConfigured = Boolean(process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID);
  return <main className="login-page" style={cssVars}><button className="login-customize" title="Customize login page" onClick={() => setSettingsOpen(!settingsOpen)}><Palette size={16}/> Customize</button>{settingsOpen && <ThemePanel theme={theme} onChange={setTheme} onClose={() => setSettingsOpen(false)}/>}<section className="login-art"><div className="login-brand">{logo}<div><strong>{theme.brandName}</strong><small>CONSULTATION STUDIO</small></div></div><div className="login-message"><label>GOOD HAIR DAYS, CONSIDERED.</label><h1>A better conversation<br/>starts here.</h1><p>Thoughtful consultations for guests. A clearer point of view for every stylist.</p></div><div className="login-art-footer"><span><Sparkles size={15}/> Human judgement, beautifully supported.</span><small>Personalized wherever you are</small></div></section><section className="login-panel"><div className="login-form"><div className="mobile-login-brand">{logo}<b>{theme.brandName}</b></div><label className="eyebrow">WELCOME BACK</label><h2>Sign in to {theme.brandName}</h2><p className="login-copy">Choose your workspace to continue.</p><div className="role-toggle"><button className={role === 'user' ? 'selected' : ''} onClick={() => setRole('user')}><UserRound size={16}/><span><b>Guest</b><small>Book an appointment</small></span></button><button className={role === 'admin' ? 'selected' : ''} onClick={() => setRole('admin')}><LockKeyhole size={16}/><span><b>Admin</b><small>Manage the studio</small></span></button></div><label className="login-label">Email address</label><input value={email} onChange={event => setEmail(event.target.value)} placeholder="Enter your email" type="email"/><label className="login-label">Password</label><input value={password} onChange={event => setPassword(event.target.value)} placeholder="Enter your password" type="password"/><div className="login-row"><label><input type="checkbox"/> Remember me</label><button type="button" onClick={() => { window.history.pushState({}, '', '/forgot-password'); window.location.reload(); }}>Forgot password?</button></div><button className="primary wide login-submit" onClick={() => void onLogin(email, password, role, theme)}>Continue as {role === 'admin' ? 'admin' : 'guest'} <ArrowRight size={17}/></button>{googleConfigured ? <div className="google-login" aria-label="Continue with Google" /> : <button className="soft wide google-login-disabled" disabled title="Configure NEXT_PUBLIC_GOOGLE_CLIENT_ID to enable Google sign-in">Continue with Google</button>}{error && <p className="login-error">{error}</p>}<p className="demo-hint"><Check size={14}/> Sign in securely to continue.</p></div></section></main>;
}
