import { useState } from 'react';
import { Check, FileText, Heart, MapPin, Plus } from 'lucide-react';
import { passportStyles } from '../data/dummy';
import { ShellTitle } from '../components/ShellTitle';

export function PassportScreen({ onNew }: { onNew: () => void }) {
  const [favorites, setFavorites] = useState<string[]>(['Soft textured lob']);
  const toggleFavorite = (name: string) => setFavorites(favorites.includes(name) ? favorites.filter(item => item !== name) : [...favorites, name]);
  return <section className="page passport"><ShellTitle eyebrow="THE LONG VIEW OF STYLE" title="Hair Passport" copy="A living record of what makes a guest feel most like themselves. Bring it into every future conversation." action={<button className="primary" onClick={onNew}><Plus size={17}/>New consultation</button>}/><div className="passport-grid"><div><section className="panel guest-card"><div className="guest-hero"><span className="avatar large yellow">AR</span><label>GUEST PROFILE</label><h2>Ananya Rao</h2><p><MapPin size={14}/>Indiranagar · Bengaluru</p></div><div className="guest-facts"><p><span>Last visit</span><b>18 June 2024</b></p><p><span>Hair profile</span><b>Wavy · Shoulder length</b></p><p><span>Preferred stylist</span><b>Meera Nair</b></p><hr/><label>PREFERENCES</label><div className="tags"><em>Low maintenance</em><em>Soft movement</em><em>Warm tones</em></div></div></section><section className="panel memory"><label>NOTES THAT STAY</label><h2>Stylist memory</h2><FileText size={19}/><textarea defaultValue="Prefers low-maintenance shapes that still feel polished for work."/><button className="soft wide"><Check size={15}/>Save note</button></section><section className="panel before-after"><label>THE JOURNEY</label><h2>Before & after</h2><div className="comparison"><div><span>BEFORE</span><b>18 Jun</b></div><div><span>AFTER</span><b>Saved look</b></div></div><button className="soft wide"><Plus size={15}/>Add final look</button></section></div><div><section className="panel favourites"><div className="panel-head"><div><label>A POINT OF VIEW</label><h2>Favourite styles</h2></div><button className="soft"><Heart size={15}/>Add style</button></div><div className="style-grid">{passportStyles.map(style => <div className="style-card" key={style.name}><div className={`style-art ${style.tone}`}><span/></div><div><b>{style.name}</b><small>{style.meta}</small></div><button className="style-favorite" title="Toggle favorite" onClick={() => toggleFavorite(style.name)}><Heart size={15} fill={favorites.includes(style.name) ? 'currentColor' : 'none'}/></button></div>)}</div></section><section className="panel history"><div className="panel-head"><div><label>THE RECORD</label><h2>Service history</h2></div><button className="text-button">View all</button></div>{[['18 Jun 2024','Signature cut','Meera Nair · Soft textured lob'],['14 May 2024','Gloss refresh','Meera Nair · Warm espresso'],['02 Mar 2024','Shape-up','Arjun Shah · Air-dried movement']].map(item => <div className="history-row" key={item[0]}><small>{item[0]}</small><div><b>{item[1]}</b><span>{item[2]}</span></div><Check size={15}/></div>)}</section></div></div></section>;
}
