import { useState } from 'react';
import { Check, FileText, Heart, MapPin, Plus } from 'lucide-react';
import { ShellTitle } from '../components/ShellTitle';
import type { Passport } from '../types';

export function PassportScreen({ passport, onBack, onNew, onSave }: { passport: Passport; onBack: () => void; onNew: () => void; onSave: (changes: Partial<Passport>) => void }) {
  const [favorites, setFavorites] = useState<string[]>([passport.styles[0]?.name || '']);
  const [notes, setNotes] = useState(passport.notes);
  const toggleFavorite = (name: string) => setFavorites(favorites.includes(name) ? favorites.filter(item => item !== name) : [...favorites, name]);
  const saveNotes = () => onSave({ notes });
  return <section className="page passport"><ShellTitle eyebrow="THE LONG VIEW OF STYLE" title="Hair Passport" copy="A living record of what makes a guest feel most like themselves. Bring it into every future conversation." back="Back to today" onBack={onBack} action={<button className="primary" onClick={onNew}><Plus size={17}/>New consultation</button>}/><div className="passport-grid"><div><section className="panel guest-card"><div className="guest-hero"><span className="avatar large yellow">{passport.guestName.split(' ').map(part => part[0]).join('')}</span><label>GUEST PROFILE</label><h2>{passport.guestName}</h2><p><MapPin size={14}/>{passport.location}</p></div><div className="guest-facts"><p><span>Last visit</span><b>{passport.history[0]?.date || 'No visits yet'}</b></p><p><span>Hair profile</span><b>{passport.texture} · {passport.length}</b></p><p><span>Preferred stylist</span><b>{passport.preferredStylist}</b></p><hr/><label>PREFERENCES</label><div className="tags">{passport.preferences.map(item => <em key={item}>{item}</em>)}</div></div></section><section className="panel memory"><label>NOTES THAT STAY</label><h2>Stylist memory</h2><FileText size={19}/><textarea value={notes} onChange={event => setNotes(event.target.value)}/><button className="soft wide" onClick={saveNotes}><Check size={15}/>Save note</button></section><section className="panel before-after"><label>THE JOURNEY</label><h2>Before & after</h2><div className="comparison"><div><img src={passport.beforeImage} alt="Before current hair look"/><span>BEFORE</span><b>{passport.history[0]?.date || 'Current'}</b></div><div><img src={passport.afterImage} alt="After saved hairstyle"/><span>AFTER</span><b>Saved look</b></div></div><button className="soft wide"><Plus size={15}/>Add final look</button></section></div><div><section className="panel favourites"><div className="panel-head"><div><label>A POINT OF VIEW</label><h2>Favourite styles</h2></div><button className="soft"><Heart size={15}/>Add style</button></div><div className="style-grid">{passport.styles.map(style => <div className="style-card" key={style.name}><div className={`style-art ${style.tone}`}><img src={style.image} alt={style.name}/></div><div><b>{style.name}</b><small>{style.meta}</small></div><button className="style-favorite" title="Toggle favorite" onClick={() => toggleFavorite(style.name)}><Heart size={15} fill={favorites.includes(style.name) ? 'currentColor' : 'none'}/></button></div>)}</div></section><section className="panel history"><div className="panel-head"><div><label>THE RECORD</label><h2>Service history</h2></div><button className="text-button">View all</button></div>{passport.history.map(item => <div className="history-row" key={`${item.date}-${item.service}`}><small>{item.date}</small><div><b>{item.service}</b><span>{item.detail}</span></div><Check size={15}/></div>)}</section></div></div></section>;
}
