import { useEffect, useState } from 'react';
import { ArrowLeft, Check } from 'lucide-react';
import { request } from '../api';

export function PasswordRecoveryScreen({ mode, onBack }: { mode: 'forgot' | 'reset' | 'verify'; onBack: () => void }) {
  const token = new URLSearchParams(window.location.search).get('token') || '';
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (mode === 'verify' && token) void request<{ message: string }>(`/auth/verify-email?token=${encodeURIComponent(token)}`).then(result => setMessage(result.message)).catch(() => setError('This verification link is invalid or expired.')); }, [mode, token]);
  const submit = async () => { setError(''); setMessage(''); try { const result = mode === 'forgot' ? await request<{ message: string }>('/auth/forgot-password', { method: 'POST', body: JSON.stringify({ email }) }) : await request<{ message: string }>('/auth/reset-password', { method: 'POST', body: JSON.stringify({ token, password }) }); setMessage(result.message); } catch { setError('We could not complete that request. Please check the details and try again.'); } };
  return <main className="login-page recovery-page"><section className="login-panel"><div className="login-form"><button className="text-button" onClick={onBack}><ArrowLeft size={15}/>Back to sign in</button><label className="eyebrow">ACCOUNT SECURITY</label><h2>{mode === 'forgot' ? 'Reset your password' : mode === 'reset' ? 'Choose a new password' : 'Verify your email'}</h2>{mode === 'verify' ? <p className={error ? 'login-error' : 'demo-hint'}>{error || message || 'Verifying your email...'}</p> : <>{mode === 'forgot' && <><p className="login-copy">Enter your email and we will send a reset link if an account exists.</p><label className="login-label">Email address</label><input value={email} onChange={event => setEmail(event.target.value)} type="email" autoComplete="email" /></>}{mode === 'reset' && <><p className="login-copy">Choose a password with at least 8 characters.</p><label className="login-label">New password</label><input value={password} onChange={event => setPassword(event.target.value)} type="password" autoComplete="new-password" /></>}<button className="primary wide" onClick={() => void submit()}><Check size={16}/>{mode === 'forgot' ? 'Send reset link' : 'Save new password'}</button>{message && <p className="demo-hint">{message}</p>}{error && <p className="login-error">{error}</p>}</>}</div></section></main>;
}
