import { useEffect, useState } from 'react';
import { ImagePlus, Package, Plus, Save, Trash2 } from 'lucide-react';
import { ShellTitle } from '../components/ShellTitle';
import { useToast } from '../components/Toast';
import { authenticatedImageUrl, uploadFile } from '../api';
import type { ProductItem, Role } from '../types';

const newProduct = (): ProductItem => ({ id: `product-${Date.now()}`, name: '', description: '', imageUrl: '', active: true });

export function ProductsScreen({ role, products, onBack, onSave }: { role: Role; products: ProductItem[]; onBack: () => void; onSave?: (items: ProductItem[]) => void | Promise<void> }) {
  const [draft, setDraft] = useState(products);
  const [saving, setSaving] = useState(false);
  const { showToast } = useToast();
  useEffect(() => setDraft(products), [products]);
  const update = (id: string, changes: Partial<ProductItem>) => setDraft(items => items.map(item => item.id === id ? { ...item, ...changes } : item));
  const save = async () => { if (!onSave) return; const items = draft.filter(item => item.name.trim()).map(item => ({ ...item, name: item.name.trim(), active: item.active !== false })); setSaving(true); try { await onSave(items); showToast('Product catalog saved.'); } catch (error) { showToast(error instanceof Error ? error.message : 'Could not save the product catalog.', 'error'); } finally { setSaving(false); } };
  const upload = async (id: string, file: File | undefined) => { if (!file) return; try { const asset = await uploadFile(file); update(id, { imageUrl: `${(typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_API_URL) || 'http://localhost:3000'}${asset.url}` }); showToast('Product image uploaded. Save the catalog to publish it.'); } catch (error) { showToast(error instanceof Error ? error.message : 'Could not upload the product image.', 'error'); } };
  const visible = role === 'admin' ? draft : products.filter(item => item.active !== false);
  return <section className="page products-page"><ShellTitle eyebrow={role === 'admin' ? 'PRODUCT CATALOG' : 'SALON PRODUCTS'} title={role === 'admin' ? 'Show guests what you use.' : 'Products used in the salon.'} copy={role === 'admin' ? 'Add the professional brands and products used by your team.' : 'See the professional products your salon uses during services.'} back={role === 'admin' ? 'Back to studio data' : 'Back to appointments'} onBack={onBack} action={role === 'admin' ? <button className="primary" disabled={saving} onClick={() => void save()}><Save size={16}/>{saving ? 'Saving...' : 'Save products'}</button> : null}/>
    {role === 'admin' ? <section className="panel product-editor"><div className="section-label"><span className="round-icon sage"><Package size={16}/></span><div><b>Products used in the salon</b><small>Only active products are visible to guests.</small></div></div>{visible.map(item => <div className="product-editor-row" key={item.id}><div className="product-editor-fields"><input value={item.name} placeholder="Brand or product name" onChange={event => update(item.id, { name: event.target.value })}/><input value={item.description || ''} placeholder="Short description" onChange={event => update(item.id, { description: event.target.value })}/><label className="preference-row"><input type="checkbox" checked={item.active !== false} onChange={event => update(item.id, { active: event.target.checked })}/>Show to guests</label>{item.imageUrl && <img className="product-thumb" src={authenticatedImageUrl(item.imageUrl)} alt={`${item.name} product`} />}</div><label className="soft product-upload"><ImagePlus size={15}/>Upload image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => void upload(item.id, event.target.files?.[0])}/></label><button className="icon-button" title="Remove product" onClick={() => setDraft(items => items.filter(product => product.id !== item.id))}><Trash2 size={15}/></button></div>)}<button className="soft" onClick={() => setDraft(items => [...items, newProduct()])}><Plus size={15}/>Add product</button>{!draft.length && <p className="empty-appointments">No products yet. Add the brands your salon uses.</p>}</section> : <section className="product-grid">{visible.map(item => <article className="panel product-card" key={item.id}>{item.imageUrl ? <img src={authenticatedImageUrl(item.imageUrl)} alt={`${item.name} product`} /> : <div className="product-placeholder"><Package size={28}/></div>}<div><h2>{item.name}</h2><p>{item.description || 'Professional products used by the salon team.'}</p></div></article>)}{!visible.length && <section className="panel empty-appointments"><Package size={20}/><p>The salon has not published its product list yet.</p></section>}</section>}
  </section>;
}
