import { useEffect, useState } from 'react';
import { Check, MapPin, Plus, Scissors, Trash2, UserRound } from 'lucide-react';
import { ShellTitle } from '../components/ShellTitle';
import { useToast } from '../components/Toast';
import { SalonMediaUploadPanel } from '../components/SalonMediaUploadPanel';
import type { SalonBranch, SalonConfig } from '../types';

const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const emptyDetail = (name: string) => ({ name, durationMinutes: 60, price: 0, imageUrl: '' });
const emptyBranch = (name: string, location: string, config: SalonConfig): SalonBranch => ({ id: `${Date.now()}`, name, location, contact: '', active: true, openingHours: { ...config.openingHours }, closedDays: [...config.closedDays], services: [...config.services], stylists: [...config.stylists] });

export function SalonSetupScreen({ config, onBack, onSave }: { config: SalonConfig; onBack: () => void; onSave: (config: SalonConfig) => void | Promise<void> }) {
  const [draft, setDraft] = useState(config);
  const [service, setService] = useState('');
  const [stylist, setStylist] = useState('');
  const [leaveDates, setLeaveDates] = useState<Record<string, string>>({});
  const [activeTab, setActiveTab] = useState<'setup' | 'media'>('setup');
  const { showToast } = useToast();
  useEffect(() => setDraft(config), [config]);
  const details = draft.serviceDetails || draft.services.map(emptyDetail);
  const schedules = draft.stylistSchedules || {};
  const profiles = draft.stylistProfiles || {};
  const branches = draft.branches?.length ? draft.branches : [emptyBranch(draft.name, draft.location, draft)];
  const updateBranch = (id: string, changes: Partial<SalonBranch>) => setDraft(current => ({ ...current, branches: (current.branches || branches).map(branch => branch.id === id ? { ...branch, ...changes } : branch) }));
  const toggleBranchDay = (branch: SalonBranch, day: string) => updateBranch(branch.id, { closedDays: branch.closedDays.includes(day) ? branch.closedDays.filter(item => item !== day) : [...branch.closedDays, day] });
  const toggleBranchItem = (branch: SalonBranch, key: 'services' | 'stylists', value: string) => {
    const all = key === 'services' ? draft.services : draft.stylists;
    const selected = branch[key]?.length ? branch[key] : all;
    updateBranch(branch.id, { [key]: selected.includes(value) ? selected.filter(item => item !== value) : [...selected, value] });
  };
  const save = () => {
    const activeBranches = branches.filter(branch => branch.active !== false);
    const names = activeBranches.map(branch => branch.name.trim().toLowerCase());
    if (!draft.name.trim() || !draft.location.trim()) { showToast('Salon name and location are required.', 'error'); return; }
    if (draft.openingHours.open >= draft.openingHours.close) { showToast('Salon opening time must be before closing time.', 'error'); return; }
    if (!activeBranches.length || new Set(names).size !== names.length) { showToast('Add one active branch with unique names.', 'error'); return; }
    if (activeBranches.some(branch => !branch.name.trim() || !branch.location.trim() || branch.openingHours.open >= branch.openingHours.close)) { showToast('Check each branch name, location, and hours.', 'error'); return; }
    const next = { ...draft, serviceDetails: details, branches: branches.map(branch => ({ ...branch, name: branch.name.trim(), location: branch.location.trim(), contact: branch.contact?.trim() || '', active: branch.active !== false })), stylistProfiles: profiles, services: draft.services.length ? draft.services : ['Consultation'], stylists: draft.stylists.length ? draft.stylists : ['Any available stylist'] };
    void Promise.resolve(onSave(next)).then(() => showToast('Salon details saved.')).catch(error => showToast(error instanceof Error ? error.message : 'Could not save salon details.', 'error'));
  };
  const toggle = (key: 'closedDays', value: string) => setDraft(current => ({ ...current, [key]: current[key].includes(value) ? current[key].filter(item => item !== value) : [...current[key], value] }));
  const addService = () => { const name = service.trim(); if (!name || draft.services.includes(name)) return; setDraft(current => ({ ...current, services: [...current.services, name], serviceDetails: [...(current.serviceDetails || current.services.map(emptyDetail)), emptyDetail(name)] })); setService(''); };
  const addStylist = () => { const name = stylist.trim(); if (!name || draft.stylists.includes(name)) return; setDraft(current => ({ ...current, stylists: [...current.stylists, name] })); setStylist(''); };
  const updateProfile = (name: string, key: 'bio' | 'imageUrl', value: string) => setDraft(current => ({ ...current, stylistProfiles: { ...(current.stylistProfiles || {}), [name]: { bio: current.stylistProfiles?.[name]?.bio || '', imageUrl: current.stylistProfiles?.[name]?.imageUrl || '', [key]: value } } }));
  const toggleWorkingDay = (name: string, day: string) => setDraft(current => ({ ...current, stylistSchedules: { ...(current.stylistSchedules || {}), [name]: { workingDays: (current.stylistSchedules?.[name]?.workingDays || days.filter(item => !current.closedDays.includes(item))).includes(day) ? (current.stylistSchedules?.[name]?.workingDays || []).filter(item => item !== day) : [...(current.stylistSchedules?.[name]?.workingDays || days.filter(item => !current.closedDays.includes(item))), day], leaveDates: current.stylistSchedules?.[name]?.leaveDates || [] } } }));
  const addLeave = (name: string) => { const date = leaveDates[name]; if (!date) return; setDraft(current => ({ ...current, stylistSchedules: { ...(current.stylistSchedules || {}), [name]: { workingDays: current.stylistSchedules?.[name]?.workingDays || days, leaveDates: [...new Set([...(current.stylistSchedules?.[name]?.leaveDates || []), date])] } } })); setLeaveDates(current => ({ ...current, [name]: '' })); };

  return <section className="page salon-setup"><ShellTitle eyebrow="STUDIO SETUP" title="Shape the booking experience." copy="Manage branches, services, prices, stylist profiles, schedules, leave, and private media." back="Back to studio data" onBack={onBack} action={<span className="ready-pill">DATABASE CONNECTED</span>} /><div className="salon-setup-tabs" role="tablist" aria-label="Salon setup sections"><button type="button" role="tab" aria-selected={activeTab === 'setup'} className={activeTab === 'setup' ? 'soft' : 'text-button'} onClick={() => setActiveTab('setup')}>Salon setup</button><button type="button" role="tab" aria-selected={activeTab === 'media'} className={activeTab === 'media' ? 'soft' : 'text-button'} onClick={() => setActiveTab('media')}>Private image uploads</button></div>{activeTab === 'setup' ? <div className="setup-grid"><section className="panel form-panel">
    <div className="section-label"><span className="round-icon peach"><MapPin size={16} /></span><div><b>Branches and hours</b><small>Guests choose a branch before selecting a service and stylist.</small></div></div>
    <div className="field"><label>Salon name</label><input value={draft.name} onChange={event => setDraft(current => ({ ...current, name: event.target.value }))} /></div><div className="field"><label>Main location</label><input value={draft.location} onChange={event => setDraft(current => ({ ...current, location: event.target.value }))} /></div>
    <div className="form-two"><label className="field"><span>Default opening</span><input type="time" value={draft.openingHours.open} onChange={event => setDraft(current => ({ ...current, openingHours: { ...current.openingHours, open: event.target.value } }))} /></label><label className="field"><span>Default closing</span><input type="time" value={draft.openingHours.close} onChange={event => setDraft(current => ({ ...current, openingHours: { ...current.openingHours, close: event.target.value } }))} /></label></div>
    <div className="field"><label>Default closed days</label><div className="tags">{days.map(day => <button type="button" className={draft.closedDays.includes(day) ? 'soft' : 'text-button'} key={day} onClick={() => toggle('closedDays', day)}>{day.slice(0, 3)}</button>)}</div></div>
    <div className="setup-list branch-list">{branches.map(branch => <div className="setup-item branch-setup-item" key={branch.id}><div><div className="branch-heading"><b>{branch.name || 'New branch'}</b><label className="preference-row"><input type="checkbox" checked={branch.active !== false} onChange={event => updateBranch(branch.id, { active: event.target.checked })} />Active</label></div><div className="form-two"><input value={branch.name} aria-label="Branch name" placeholder="Branch name" onChange={event => updateBranch(branch.id, { name: event.target.value })} /><input value={branch.location} aria-label="Branch location" placeholder="Address or location" onChange={event => updateBranch(branch.id, { location: event.target.value })} /></div><input value={branch.contact || ''} aria-label="Branch contact" placeholder="Contact phone or email" onChange={event => updateBranch(branch.id, { contact: event.target.value })} /><div className="form-two"><label className="field"><span>Opening</span><input type="time" value={branch.openingHours.open} onChange={event => updateBranch(branch.id, { openingHours: { ...branch.openingHours, open: event.target.value } })} /></label><label className="field"><span>Closing</span><input type="time" value={branch.openingHours.close} onChange={event => updateBranch(branch.id, { openingHours: { ...branch.openingHours, close: event.target.value } })} /></label></div><label className="branch-label">Closed days</label><div className="tags">{days.map(day => <button type="button" className={branch.closedDays.includes(day) ? 'soft' : 'text-button'} key={day} onClick={() => toggleBranchDay(branch, day)}>{day.slice(0, 3)}</button>)}</div><label className="branch-label">Services at this branch</label><div className="tags">{draft.services.map(item => <button type="button" className={(branch.services?.length ? branch.services : draft.services).includes(item) ? 'soft' : 'text-button'} key={item} onClick={() => toggleBranchItem(branch, 'services', item)}>{item}</button>)}</div><label className="branch-label">Stylists at this branch</label><div className="tags">{draft.stylists.map(item => <button type="button" className={(branch.stylists?.length ? branch.stylists : draft.stylists).includes(item) ? 'soft' : 'text-button'} key={item} onClick={() => toggleBranchItem(branch, 'stylists', item)}>{item}</button>)}</div></div><button className="icon-button" title="Remove branch" onClick={() => setDraft(current => ({ ...current, branches: (current.branches || branches).filter(item => item.id !== branch.id) }))}><Trash2 size={14} /></button></div>)}</div>
    <div className="add-row"><input id="new-branch" placeholder="Branch name · location" /><button className="soft" onClick={() => { const input = document.getElementById('new-branch') as HTMLInputElement; const [name, location] = input.value.split('·').map(item => item.trim()); if (name) { setDraft(current => ({ ...current, branches: [...(current.branches || branches), emptyBranch(name, location || name, current)] })); input.value = ''; } }}><Plus size={15} />Add branch</button></div>
    <hr /><div className="section-label"><span className="round-icon butter"><Scissors size={16} /></span><div><b>Services, price, duration, and image</b><small>Shown in the guest booking catalog.</small></div></div><div className="setup-list">{draft.services.map(name => { const item = details.find(detail => detail.name === name) || emptyDetail(name); return <div className="setup-item" key={name}><div><b>{name}</b><div className="form-two"><input type="number" min="15" step="15" value={item.durationMinutes} aria-label={`${name} duration`} onChange={event => setDraft(current => ({ ...current, serviceDetails: (current.serviceDetails || details).map(detail => detail.name === name ? { ...detail, durationMinutes: Number(event.target.value) } : detail) }))} /><input type="number" min="0" step="100" value={item.price} aria-label={`${name} price`} onChange={event => setDraft(current => ({ ...current, serviceDetails: (current.serviceDetails || details).map(detail => detail.name === name ? { ...detail, price: Number(event.target.value) } : detail) }))} /></div><input value={item.imageUrl || ''} placeholder="Service image URL" onChange={event => setDraft(current => ({ ...current, serviceDetails: (current.serviceDetails || details).map(detail => detail.name === name ? { ...detail, imageUrl: event.target.value } : detail) }))} /></div><button className="icon-button" title="Remove service" onClick={() => setDraft(current => ({ ...current, services: current.services.filter(item => item !== name), serviceDetails: (current.serviceDetails || []).filter(item => item.name !== name) }))}><Trash2 size={14} /></button></div>; })}</div><div className="add-row"><input value={service} onChange={event => setService(event.target.value)} placeholder="Add a service" /><button className="soft" onClick={addService}><Plus size={15} />Add</button></div>
    <hr /><div className="section-label"><span className="round-icon sage"><UserRound size={16} /></span><div><b>Stylist profiles and availability</b><small>Working days, leave dates, bio, and profile image.</small></div></div><div className="setup-list">{draft.stylists.map(name => { const schedule = schedules[name] || { workingDays: days.filter(day => !draft.closedDays.includes(day)), leaveDates: [] }; const profile = profiles[name] || { bio: '', imageUrl: '' }; return <div className="setup-item" key={name}><div><b>{name}</b><div className="tags">{days.map(day => <button type="button" className={schedule.workingDays.includes(day) ? 'soft' : 'text-button'} key={day} onClick={() => toggleWorkingDay(name, day)}>{day.slice(0, 2)}</button>)}</div><div className="form-two"><input placeholder="Stylist bio" value={profile.bio} onChange={event => updateProfile(name, 'bio', event.target.value)} /><input placeholder="Profile image URL" value={profile.imageUrl} onChange={event => updateProfile(name, 'imageUrl', event.target.value)} /></div><div className="add-row"><input type="date" value={leaveDates[name] || ''} onChange={event => setLeaveDates(current => ({ ...current, [name]: event.target.value }))} /><button className="soft" onClick={() => addLeave(name)}><Plus size={13} />Add leave</button></div><small>{schedule.leaveDates.join(' · ') || 'No leave dates'}</small></div><button className="icon-button" title="Remove stylist" onClick={() => setDraft(current => ({ ...current, stylists: current.stylists.filter(item => item !== name) }))}><Trash2 size={14} /></button></div>; })}</div><div className="add-row"><input value={stylist} onChange={event => setStylist(event.target.value)} placeholder="Add a stylist" /><button className="soft" onClick={addStylist}><Plus size={15} />Add</button></div><button className="primary wide setup-save" onClick={save}><Check size={16} />Save salon details</button>
  </section><aside><section className="panel setup-preview"><label>GUEST PREVIEW</label><h2>{draft.name || 'Your salon'}</h2><p><MapPin size={13} /> {draft.location || 'Add a location'}</p><div className="preview-divider" /><b>Branches</b>{branches.filter(branch => branch.active !== false).map(branch => <p key={branch.id}>{branch.name} · {branch.location}</p>)}<b className="preview-label">Services</b>{draft.services.slice(0, 4).map(item => <span className="preview-chip" key={item}>{item}</span>)}</section></aside></div> : <SalonMediaUploadPanel config={config} onSave={onSave} />}</section>;
}
