import { useState } from 'react';
import { Camera, Check, ClipboardList, Sparkles, Upload, UserRound } from 'lucide-react';
import { ShellTitle } from '../components/ShellTitle';
import type { Consultation } from '../types';

type Quality = { passed: boolean; score: number; retakeGuidance: string[] };

export function ScanScreen({ consultation, onBack, onCapture, onDone, onImage, onQualityCheck }: { consultation: Consultation; onBack: () => void; onCapture: (view: string) => void; onDone: () => void; onImage: (image: string) => void; onQualityCheck: (image: string) => Promise<Quality> }) {
  const [active, setActive] = useState(0); const [captured, setCaptured] = useState<string[]>([]); const [imagePreview, setImagePreview] = useState(''); const [quality, setQuality] = useState<Quality | null>(null); const [checking, setChecking] = useState(false); const views = ['front', 'left', 'right', 'back'];
  const capture = (view: string) => { if (!captured.includes(view)) { setCaptured([...captured, view]); onCapture(view); } if (active < 2) setActive(active + 1); };
  const readImage = async (file?: File) => { if (!file) return; const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); const image = dataUrl.split(',')[1] || ''; setImagePreview(dataUrl); onImage(image); setChecking(true); try { setQuality(await onQualityCheck(image)); } finally { setChecking(false); } };
  return <section className="page scan"><ShellTitle eyebrow="02 · A QUIET GUIDED SCAN" title="Let’s see the full picture." copy={<span>Scanning <b>{consultation.guestName}</b> · keep the camera at eye level.</span>} back="Back to intake" onBack={onBack}/><div className="scan-grid"><section className="panel camera-panel"><div className="camera"><div className="camera-top"><span>{imagePreview ? 'IMAGE READY FOR REVIEW' : 'STUDIO CAMERA · READY'}</span><small><i/>{imagePreview ? 'Selected' : 'Ready'}</small></div>{imagePreview ? <img className="scan-image-preview" src={imagePreview} alt="Selected consultation source"/> : <div className="face-guide"><UserRound size={49}/><h2>{views[active][0].toUpperCase() + views[active].slice(1)} view</h2><p>Centre the face inside the guide, then<br/>hold still for one breath.</p></div>}<small className="camera-note">Images are sent to the protected AI quality API.</small><button className="capture" onClick={() => capture(views[active])}><ClipboardList size={15}/>Mark {views[active]} captured</button></div><div className="image-actions"><label className="soft"><Upload size={15}/>Upload image<input type="file" accept="image/*" onChange={event => void readImage(event.target.files?.[0])}/></label><label className="soft"><Camera size={15}/>Take photo<input type="file" accept="image/*" capture="environment" onChange={event => void readImage(event.target.files?.[0])}/></label></div>{checking && <p className="ai-checking">Checking image quality...</p>}{quality && <div className={quality.passed ? 'quality-result passed' : 'quality-result'}><b>{quality.passed ? `Image quality ready · ${quality.score}/100` : 'Retake recommended'}</b>{!quality.passed && quality.retakeGuidance.map(item => <small key={item}>{item}</small>)}</div>}</section><aside><section className="panel progress"><label>CAPTURE PROGRESS</label><h2>Three angles, one optional back.</h2><div className="progress-line"><i style={{ width: `${Math.min(captured.length / 3, 1) * 100}%` }}/></div>{views.map((view, i) => <button key={view} className={active === i ? 'view-row active' : 'view-row'} onClick={() => setActive(i)}><span>{captured.includes(view) ? <Check size={15}/> : i + 1}</span><div><b>{view[0].toUpperCase() + view.slice(1)} view</b><small>{captured.includes(view) ? 'Captured' : active === i ? 'Ready to capture' : view === 'back' ? 'Optional' : 'Waiting'}</small></div><i/></button>)}</section><section className="panel quality"><label>QUALITY CHECKLIST</label>{['Face centred in the guide','Even natural light','Hair visible at the sides'].map(x => <p key={x}><i/><span>{x}</span></p>)}</section><button className="primary wide" disabled={!['front', 'left', 'right'].every(view => captured.includes(view))} onClick={onDone}>Analyze image <Sparkles size={16}/></button><small className="disclaimer">This is a visual estimate to support a stylist conversation. It is not a diagnosis.</small></aside></div></section>;
}
