import { useState } from 'react';
import { Check, ClipboardList, Sparkles, UserRound } from 'lucide-react';
import { ShellTitle } from '../components/ShellTitle';
import type { Consultation } from '../types';

export function ScanScreen({ consultation, onBack, onCapture, onDone }: { consultation: Consultation; onBack: () => void; onCapture: (view: string) => void; onDone: () => void }) {
  const [active, setActive] = useState(0); const [captured, setCaptured] = useState<string[]>([]); const views = ['front', 'left', 'right', 'back'];
  const capture = (view: string) => { if (!captured.includes(view)) { setCaptured([...captured, view]); onCapture(view); } if (active < 2) setActive(active + 1); };
  return <section className="page scan"><ShellTitle eyebrow="02 · A QUIET GUIDED SCAN" title="Let’s see the full picture." copy={<span>Scanning <b>{consultation.guestName}</b> · keep the camera at eye level.</span>} back="Back to intake" onBack={onBack}/><div className="scan-grid"><section className="panel camera-panel"><div className="camera"><div className="camera-top"><span>STUDIO CAMERA · SIMULATED</span><small><i/>Ready</small></div><div className="face-guide"><UserRound size={49}/><h2>{views[active][0].toUpperCase() + views[active].slice(1)} view</h2><p>Centre the face inside the guide, then<br/>hold still for one breath.</p></div><small className="camera-note">No photo leaves this prototype.</small><button className="capture" onClick={() => capture(views[active])}><ClipboardList size={15}/>Capture {views[active]}</button></div></section><aside><section className="panel progress"><label>CAPTURE PROGRESS</label><h2>Three angles, one optional back.</h2><div className="progress-line"><i style={{ width: `${Math.min(captured.length / 3, 1) * 100}%` }}/></div>{views.map((view, i) => <button key={view} className={active === i ? 'view-row active' : 'view-row'} onClick={() => setActive(i)}><span>{captured.includes(view) ? <Check size={15}/> : i + 1}</span><div><b>{view[0].toUpperCase() + view.slice(1)} view</b><small>{captured.includes(view) ? 'Captured' : active === i ? 'Ready to capture' : view === 'back' ? 'Optional' : 'Waiting'}</small></div><i/></button>)}</section><section className="panel quality"><label>QUALITY CHECKLIST</label>{['Face centred in the guide','Even natural light','Hair visible at the sides'].map(x => <p key={x}><i/><span>{x}</span></p>)}</section><button className="primary wide" disabled={!['front', 'left', 'right'].every(view => captured.includes(view))} onClick={onDone}>Simulate analysis <Sparkles size={16}/></button><small className="disclaimer">This is a visual estimate to support a stylist conversation. It is not a diagnosis.</small></aside></div></section>;
}
