import { useEffect, useState } from 'react';
import { Bell, Check, CreditCard, FileText, MessageSquare, Printer, Save, Star, X } from 'lucide-react';
import { ShellTitle } from '../components/ShellTitle';
import { useToast } from '../components/Toast';
import { request } from '../api';
import type { Appointment, Role } from '../types';

type Review = { id: string; guestName: string; rating: number; comment: string; status: 'Pending' | 'Published' | 'Rejected'; createdAt: string };
type Payment = { id: string; appointmentId: string; guestEmail: string; provider: string; subtotal: number; discount: number; tax: number; total: number; currency: string; status: 'Pending' | 'Paid' | 'Failed' | 'Refunded'; invoiceNumber: string; createdAt: string; };

export function ToolsScreen({ role, appointments }: { role: Role; appointments: Appointment[] }) {
  const { showToast } = useToast();
  const [reviews, setReviews] = useState<Review[]>([]);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [rating, setRating] = useState(5);
  const [comment, setComment] = useState('');
  const [message, setMessage] = useState('');
  const [preferences, setPreferences] = useState({ email: true, sms: false, whatsapp: false });
  const refreshPayments = () => void request<Payment[]>('/payments').then(setPayments).catch(() => setPayments([]));
  useEffect(() => { void request<Review[]>('/reviews').then(setReviews).catch(() => setReviews([])); void request<typeof preferences>('/auth/preferences').then(setPreferences).catch(() => undefined); refreshPayments(); }, []);
  const submitReview = async () => { if (!comment.trim()) return; try { await request('/reviews', { method: 'POST', body: JSON.stringify({ rating, comment, appointmentId: appointments[0]?.id }) }); setComment(''); setMessage(''); showToast('Review submitted for approval.'); } catch { setMessage('Sign in to submit a review.'); showToast('Could not submit the review.', 'error'); } };
  const updateReview = async (id: string, status: 'Published' | 'Rejected') => { try { const saved = await request<Review>(`/reviews/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); setReviews(items => items.map(item => item.id === id ? saved : item)); showToast(`Review ${status.toLowerCase()}.`); } catch { setMessage('Could not update this review.'); showToast('Could not update this review.', 'error'); } };
  const savePreferences = async () => { try { setPreferences(await request<typeof preferences>('/auth/preferences', { method: 'PUT', body: JSON.stringify(preferences) })); setMessage(''); showToast('Notification preferences saved.'); } catch { setMessage('Could not save notification preferences.'); showToast('Could not save notification preferences.', 'error'); } };
  const createPayment = async (appointment: Appointment) => { try { await request<Payment>('/payments/intent', { method: 'POST', body: JSON.stringify({ appointmentId: appointment.id, idempotencyKey: `${appointment.id}-checkout` }) }); refreshPayments(); showToast('Payment recorded and invoice created.'); } catch (error) { showToast(error instanceof Error ? error.message : 'Could not create the payment.', 'error'); } };
  const invoiceAppointment = (payment: Payment) => appointments.find(appointment => appointment.id === payment.appointmentId);

  return <section className="page tools"><ShellTitle eyebrow={role === 'admin' ? 'STUDIO MANAGEMENT' : 'YOUR ACCOUNT'} title={role === 'admin' ? 'Keep the conversation thoughtful.' : 'Keep your salon relationship close.'} copy={role === 'admin' ? 'Review guest feedback and keep the studio experience consistent.' : 'Manage feedback, notifications, and appointment payment records.'} action={<span className="guest-pill">{role === 'admin' ? 'ADMIN' : 'GUEST'}</span>} /><div className="data-grid">
    <section className="panel form-panel"><div className="section-label"><span className="round-icon peach"><MessageSquare size={16} /></span><div><b>{role === 'admin' ? 'Review moderation' : 'Share your experience'}</b><small>{role === 'admin' ? 'Publish or reject submitted feedback.' : 'Your review is sent to the salon for approval.'}</small></div></div>{role === 'admin' ? reviews.map(review => <div className="review-row" key={review.id}><div><b>{review.guestName} · {'★'.repeat(review.rating)}</b><p>{review.comment}</p><small>{review.status}</small></div>{review.status === 'Pending' && <span><button className="icon-button" title="Publish review" onClick={() => void updateReview(review.id, 'Published')}><Check size={16} /></button><button className="icon-button" title="Reject review" onClick={() => void updateReview(review.id, 'Rejected')}><X size={16} /></button></span>}</div>) : <><div className="rating-picker">{[1, 2, 3, 4, 5].map(value => <button type="button" key={value} title={`${value} stars`} onClick={() => setRating(value)}><Star size={24} fill={value <= rating ? 'currentColor' : 'none'} /></button>)}</div><textarea className="appointment-notes" value={comment} onChange={event => setComment(event.target.value)} placeholder="Tell us about your visit..." /><button className="primary" onClick={() => void submitReview()}><MessageSquare size={16} />Submit review</button></>}</section>
    <div><section className="panel form-panel"><div className="section-label"><span className="round-icon sage"><Bell size={16} /></span><div><b>Notification preferences</b><small>Choose which reminders you want to receive.</small></div></div>{(['email', 'sms', 'whatsapp'] as const).map(channel => <label className="preference-row" key={channel}><input type="checkbox" checked={preferences[channel]} onChange={event => setPreferences(current => ({ ...current, [channel]: event.target.checked }))} /><span>{channel === 'email' ? 'Email reminders' : channel === 'sms' ? 'SMS reminders' : 'WhatsApp reminders'}</span></label>)}<button className="soft wide" onClick={savePreferences}><Save size={15} />Save preferences</button></section>
      <section className="panel form-panel invoice-panel"><div className="section-label"><span className="round-icon butter"><CreditCard size={16} /></span><div><b>Payments and invoices</b><small>Payments are stored with an idempotent invoice record.</small></div></div>{appointments.filter(appointment => appointment.status !== 'Cancelled').slice(0, 5).map(appointment => { const payment = payments.find(item => item.appointmentId === appointment.id); return <div className="invoice-row" key={appointment.id}><div><b>{appointment.service}</b><small>{appointment.date} · {appointment.status} · {payment ? payment.invoiceNumber : 'No invoice yet'}</small></div>{payment ? <span className={`payment-status ${payment.status.toLowerCase()}`}>{payment.status} · ₹{payment.total.toLocaleString('en-IN')}<button className="icon-button" title="Print invoice" onClick={() => window.print()}><Printer size={13} /></button></span> : <button className="soft invoice-pay" onClick={() => void createPayment(appointment)}><FileText size={14} />Create invoice</button>}</div>; })}{!appointments.length && <p>No appointment invoices yet.</p>}{payments.length > appointments.length && payments.filter(payment => !invoiceAppointment(payment)).map(payment => <div className="invoice-row" key={payment.id}><div><b>{payment.invoiceNumber}</b><small>Payment record</small></div><span className={`payment-status ${payment.status.toLowerCase()}`}>{payment.status} · ₹{payment.total.toLocaleString('en-IN')}<button className="icon-button" title="Print invoice" onClick={() => window.print()}><Printer size={13} /></button></span></div>)}</section></div>
  </div>{message && <p className="save-error">{message}</p>}</section>;
}
